<?xml version="1.0"?>
<package format="3">
  <name>uav_bringup</name>
  <version>0.1.0</version>
  <description>PX4 1.14.3 仿真与真机共用算法入口</description>
  <maintainer email="team@example.com">rm27-uav</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>uav_msgs</exec_depend>
  <exec_depend>uav_control</exec_depend>
  <exec_depend>uav_swarm</exec_depend>
  <exec_depend>uav_perception</exec_depend>
  <exec_depend>uav_planning</exec_depend>
  <exec_depend>uav_mapping</exec_depend>
  <exec_depend>uav_rviz_plugins</exec_depend>
  <exec_depend>uav_localization</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
